### PR TITLE
Improve Proposal in Multiple Scalaversion Error Case

### PR DESCRIPTION
**Pull request by PSeitz**
I think this message would helped me more

### CODE REVIEW

**Comment by fommil** [comment]
You should be able to infer the project name here, I think.

**Comment by PSeitz** [comment]
In my ensime.sbt this didn't work:
`ensimeIgnoreScalaMismatch := true`

But this did:
`ensimeIgnoreScalaMismatch in LocalProject("project-to-ignore") := true`

I couldn't find something in the documentation about LocalProject, only a comment in a bug (https://github.com/ensime/ensime-sbt/issues/293)
http://ensime.org/build_tools/sbt/#customise

**Comment by fommil** [comment]
Your error message can use the actual project name, not PROJECT.

**Comment by fommil** [comment]
Also doing it in ThisBuild should work, but ambiguos.

**Comment by fommil** [comment]
You dropped the bit about ensime.sbt, is that ok?

CI looks like it's borked, I'll investigate. I don't think your changes are causing it to fail.

**Comment by PSeitz** [comment]
Wasn't sure about the ensime.sbt part, but I added it back, so it's very clear what to do

**Comment by fommil** [comment]
Thanks! I'll merge and fix the build issues with a follow up.

**Pull request merged**
