### PR TITLE
[fix] filter jar and zip files

### PR DESCRIPTION
**Pull request by bomgar**
Workaround for https://github.com/ensime/ensime-sbt/issues/334

### CODE REVIEW

**Comment by bomgar** [comment]
I'm not sure if this should also include war files.

**Comment by fommil** [comment]
@bomgar you need to compile in `sbt` so that the scalariform rules are applied. Can you also please add a comment around this to reference the ticket. Use format `WORKAROUND: https://...` This way somebody won't delete it by accident. It would also be good if you could add a test in the style of the others.

**Comment by bomgar** [comment]
I tried to include the coursier plugin in a new test project. This causes the build to no longer resolve the ensime plugin in this project.

**Comment by fommil** [comment]
oooh, I think that's a known issue with coursier... you need to add the local ivy repo to the `resolvers` for that to work.

**Comment by fommil** [comment]
thanks! I'll cut a release for you.

**Comment by fommil** [comment]
1.12.12 is staging to maven central

**Pull request merged**
