### PR TITLE
ensimeCompileOnly for sbt 1.0

### PR DESCRIPTION
**Pull request by vovapolu**
https://github.com/ensime/ensime-sbt/issues/365

Adding support for `ensimeCompileOnly` in sbt 1.0.

### CODE REVIEW

**Review by fommil — APPROVED** [review]

**Comment by yyadavalli** [comment]
Awesome. @vovapolu do you think we can unify the two `CompatExtras`. I don't see why we can't add this in `EnsimeExtrasPlugin`

**Comment by fommil** [comment]
`ERROR: Error: No such image: ensime/ensime:v2.x-cache`

yeah please change to the one the ensime-server uses, there is something funky going on.

**Comment by vovapolu** [comment]
@yyadavalli Unify what? sbt 0.13 and 1.0 have quite different compiler APIs.

**Comment by yyadavalli** [comment]
@vovapolu Nevermind, I was looking at it wrong.

**Pull request merged**
