### PR TITLE
workaround cyclic dependency in scala/scala

### LINKED ISSUE #200: don't set libraryDependencies for scala and dotty
if the project name is `scala` or `dotty`, use Odersky mode and don't populate the `libraryDependencies`

### PR DESCRIPTION
**Pull request by fommil**
@milessabin whoever had this bug, please CC them.

close #200

### CODE REVIEW

**Comment by milessabin** [comment]
Paging @tpolecat.

**Comment by milessabin** [comment]
Ping me when you release this and I can update my post with full details.

**Comment by tpolecat** [comment]
👍  thanks for the quick fix!

**Comment by fommil** [comment]
I'll do a quick release tomorrow.

**Comment by fommil** [comment]
Actually there is already a snapshot release if people really want it.

**Pull request merged**
