### PR TITLE
Add your project's docs to docJars.

### PR DESCRIPTION
**Pull request by aemoncannon**
I'm not sure if this is the best approach, since I'm actually forcing the creation of the doc jar just to get the name. On the other hand, if the jar doesn't exist, there's not much point having the name. Thoughts?

### CODE REVIEW

**Comment by fommil** [comment]
hmm, I'm not too keen on this. It means that the plugin will only work for projects that can be compiled, which is a bit of a catch 22. There must be another way to do this.

**Comment by aemoncannon** [comment]
yeah good point. i'll see about just generating the path-to-be

**Comment by aemoncannon** [comment]
@fommil PTAL. Using sbt always makes me feel so dumb : \

**Comment by aemoncannon** [comment]
#fommil Ping?

**Comment by fommil** [comment]
Sorry, I wish github allowed marking threads as unread. I keep dropping actions.

**Pull request merged**
