### PR TITLE
Backup / restore

### LINKED ISSUE #379: ensimeSnapshot and ensimeRestore
My work project is modest size but we have an ungodly number of dependencies that take forever to index, but I often nuke my cache, I was considering creating a task to snapshot and restore. Basically just the grunt work of copying `.ensime_cache` to a `.ensime_snapshot` and restoring it again. Should only be a couple of lines but would be a lovely addition to my workflow. Let's see if I get to it today...

### PR DESCRIPTION
**Pull request by fommil**
close #379 

Apologies for the complete lack of tests.

### CODE REVIEW

**Comment by fommil** [comment]
@yyadavalli mind giving this a quick look over? I'm using it locally and it works quite well.

**Comment by yyadavalli** [comment]
I already looked at it, thought I could add a test before merging it.

**Comment by fommil** [comment]
FYI I have these bash aliases... 

```
alias ensime="git tidy && touch .history && ctags -Re . & sbt clean ';ensimeRestore ;ensimeConfig ;ensimeConfigProject' ensimeServerIndex"
alias ensime-compile="git tidy && touch .history && ctags -Re . & sbt clean ';ensimeRestore ;ensimeConfig ;ensimeConfigProject ;test:compile' ensimeServerIndex"

# workflow specifically for ensime-server dev
alias ensime-server="git tidy && touch .history && ctags -Re . & sbt clean ';ensimeRestore ;ensimeConfig ;ensimeConfigProject ;test:compile ;it:compile ;ensime/assembly' && sbt ensimeServerIndex && cd testing/cache && sbt ++2.12.4 ensimeConfig ensimeServerIndex && cd ../.."
```

`git tidy` is also an alias :smile: https://gitlab.com/fommil/dotfiles/blob/master/.gitconfig#L37

which means that when I start hacking on a project I rebase and type `ensime-compile` then go get some tea and it's ready when I'm back. Backup/restore means it is super fast, and if ensime ever causes me trouble I'll just type the same thing.

**Comment by yyadavalli** [comment]
Nice, should make things a lot easier. Thanks

**Comment by fommil** [comment]
Something I should have added into the docs is that it's best to run `ensimeSnapshot` on a clean version of the project, i.e. uncompiled, so it catches all (mostly static) deps but not the project class files

**Comment by fommil** [comment]
We should probably have a `ensimeCleanCache` command... especially since we always say to use it in the troubleshooting guide.

**Comment by fommil** [comment]
LGTM

**Pull request merged**
