### PR TITLE
Replace sbt commands with tasks

### PR DESCRIPTION
**Pull request by yyadavalli**

### CODE REVIEW

**Comment by yyadavalli** [comment]
@fommil I believe this is good enough to be merged. 
There are a couple of places that are still using the `BuildStructure`. One of them is the huge `projectData`, but for now I think its better to leave it in place.

**Comment by fommil** [comment]
You're my hero! I'm at a conference all week, I'll try to take a look at some point, if not ping me next week.

**Comment by yyadavalli** [comment]
Thank you. I will..,

**Comment by fommil** [comment]
you forgot to ping me! :stuck_out_tongue: There was a windows failure, but I should really look at this and merge soon

**Comment by yyadavalli** [comment]
@fommil This is ready for review. I've updated `ensimeServerVersion` to be task key.

**Comment by fommil** [comment]
Nice! I'll try to take a look soon.

**Review by fommil — APPROVED** [review]

**Comment by fommil** [comment]
omg, thank you so much!

**Pull request merged**
