### PR TITLE
removes warn-unused-import

### PR DESCRIPTION
**Pull request by hedefalk**
@fommil If I understood you correctly I could remoce this?

### CODE REVIEW

**Comment by fommil** [comment]
yup, but you'll need to laboriously update all the test assertions.

**Comment by hedefalk** [comment]
Ah, man.

**Comment by hedefalk** [comment]
@fommil One question, how dare you run drone on PR:s? You do the signing of the yml thing at least? But does it really help much? Has there been any work done there from the drone guy? I would really want to run on PR's too but I dare not.

**Comment by hedefalk** [comment]
query replace 124 occasions. Seriously? 

Was gonna try to do `drone exec` to test locally but couldn't install on my newish mac.
https://github.com/drone/homebrew-drone/issues/7

**Comment by fommil** [comment]
global search and replace :smiley:

**Comment by fommil** [comment]
I've never got local drone working, I just raise a PR

**Comment by hedefalk** [comment]
I did, but 0.4 more than a year ago.

**Comment by fommil** [comment]
it's ok, you can leave this as it is and I'll pick it up next time I'm hacking on the plugin.

**Comment by hedefalk** [comment]
I'm running scripted! No idea what it does :)

**Comment by fommil** [comment]
`scripted` is the test framework for sbt plugins, it's running our test suite every time

**Comment by jozanek** [comment]
Hey guys, does this mean I will not be able to see the unused import warning in my editor anymore?

**Comment by fommil** [comment]
@jozi-k you can add it back in again... perhaps this should be accompanied by a customisation example in the docs. Also you'll always see the unused warnings if your main build has them. They just got a bit noisy in 2.12.2

**Comment by jozanek** [comment]
The docs example to get it back would be nice. My concern is to catch as much errors/warnings as possible in editor to speed up development.

**Comment by fommil** [comment]
I am going to cut a release, I'll add this

**Comment by fommil** [comment]
I've reimplemented, will be in the next release. Man, I feel so bad... every time you raise a PR I'm too busy to merge immediately.

**Pull request closed without merging**
