### PR TITLE
Harder better faster

### PR DESCRIPTION
**Pull request by fommil**
this could perhaps be futile unless we can get past http://stackoverflow.com/questions/33988388

this is the general direction I'm wanting to go in to address the performance problems.

### CODE REVIEW

**Comment by fommil** [comment]
advice from IntelliJ https://github.com/JetBrains/sbt-structure/issues/32

**Comment by rorygraves** [comment]
Interesting stuff from the IntelliJ guys.

**Comment by fommil** [comment]
https://github.com/sbt/sbt/blob/3e5449f02d082c1326da7e6319d70d5b26b84bfd/main/src/main/scala/sbt/Act.scala#L238-L250 from josh on gitter, this is "the aggregate magic"

**Comment by fommil** [comment]
ok, I think that may be the back of the problem cracked!

**Comment by fommil** [comment]
closes #117

**Comment by fommil** [comment]
I'm going to cut a release with this, so that API changes come in 0.3.x

**Pull request merged**
