### PR TITLE
make ensimeConfigTask into an SBT key

### PR DESCRIPTION
**Pull request by paulmr**
Expose the functionality of `ensimeConfigTask` as an SBT key, so that the configuration can be overridden with code in the SBT build.

It's use is illustrated in the `build.sbt` of the test which has been included as part of this PR.

### CODE REVIEW

**Review by fommil — CHANGES_REQUESTED** [review]
Running the server index here is a bit much, but other than that this looks :+1:

**Comment by paulmr** [comment]
Thanks @fommil. Are you referring to the test script? I will remove those steps from it. Good point.

**Comment by paulmr** [comment]
@fommil done, thanks again for the review and comments.

**Review by fommil — APPROVED** [review]

**Comment by fommil** [comment]
I'll cut a release now

**Comment by fommil** [comment]
2.6.1 on its way to maven central

**Comment by fommil** [comment]
I've tried to publish this a few times, sonatype keeps timing out.

**Comment by fommil** [comment]
ok, it just went through.

**Pull request merged**
