### PR TITLE
Use the assembly jar if exists.

### PR DESCRIPTION
**Pull request by lins05**
Try to use the the locally built jar like `ensime_2.11-2.0.0-SNAPSHOT-assembly.jar` if it exists. The jar should be placed in the folder `~/.ensime/`.

### CODE REVIEW

**Comment by fommil** [comment]
oh, I was hoping this would just be a user config... i.e. in the docs. Typically if somebody wants to bypass the assembly jar they wouldn't want to depend on coursier.

**Comment by lins05** [comment]
@fommil you mean make it an option of emacs/vim, i.e. something like `ensime-use-assembly-jar` ? Yeah, that could be more flexible.

**Comment by fommil** [comment]
no, I mean make it a user config. You can just redefine what ensimeServerJars is, e.g.

```scala
ensimeServerJars := List("/my/foo-2.11.jar")
ensimeServerProjectJars := List("/my/foo-2.10.jar")
```

**Comment by lins05** [comment]
@fommil ok, I'll do that.

**Comment by fommil** [comment]
cool, I'll close this and maybe you can raise as a PR to the docs site?

**Pull request closed without merging**
