### PR TITLE
get cross-platform tests green

### LINKED ISSUE #170: Windows CI
we're not testing under AppVeyor, we should be. use ensime-server as an example

### PR DESCRIPTION
**Pull request by fommil**
close #170 and #164

### CODE REVIEW

**Comment by fommil** [comment]
```
[info] [error] [C:\Users\appveyor\AppData\Local\Temp\1\sbt_dff4c2\simple-build.scala\project\plugins.sbt]:1: illegal start of definition
```

I bet its the symbolic links.

**Comment by fommil** [comment]
https://github.com/appveyor/ci/issues/650

**Comment by fommil** [comment]
ok, cool, looks like OS X build is working! But failing because we don't have the java sources. @dwijnand did you ever work out where to download them from?

**Comment by dwijnand** [comment]
I ended up trying to use JDK 7 instead, because that had sources. Can't find the Apple JDK 6 sources anywhere for OS X 10.11..

**Comment by fommil** [comment]
JDK7 is ok for OS X and Windows builds in CI because we don't publish off there

**Comment by fommil** [comment]
in a way, we just need to `touch` the `src.zip` for this test to go through. But I'd like to work out how to get them so we can maybe enable OS X for `ensime-server` too.

**Comment by dwijnand** [comment]
`brew install homebrew/versions/java7` or `brew tap version && brew install java7` or something

**Comment by fommil** [comment]
they allow that on travis? heh. Anyway, I'm off to bed. This is **way** past my bedtime.

**Comment by dwijnand** [comment]
Is installing the necessary tools to test your project allowed in Travis' docker container? Yeah...

https://docs.travis-ci.com/user/osx-ci-environment/#Homebrew

**Comment by fommil** [comment]
sweet, OS X is green. Might just comment out the Windows one for now.

**Comment by fommil** [comment]
there are four lights

**Pull request merged**
