### PR TITLE
Standardise naming

### LINKED ISSUE #182: Rename ensime-sbt artefact to sbt-ensime
There is tremendous value in having a default naming convention for SBT plugins.
Almost all projects use `sbt-$projectname`, but `ensime-sbt` is the odd one out.

It would be great if this plugin adopted the ecosystem's naming convention!

Related ongoing changes:
 - coursier-sbt-plugin -> sbt-coursier: alexarchambault/coursier#202
 - sbteclipse-plugin -> sbt-eclipse: typesafehub/sbteclipse#314
 - android-sdk-plugin -> sbt-android: https://github.com/scala-android/sbt-android

### PR DESCRIPTION
**Pull request by fommil**
close #182 

I'm hopefully going to cut 0.5.0 when this is merged.

@soc if anybody has any problems related to the changed artefact name, the ticket is getting closed and you're getting brought in by name :stuck_out_tongue: (I mean it! This has been painful already)

### CODE REVIEW

**Comment by fommil** [comment]
@dwijnand @rorygraves thoughts?

**Comment by rorygraves** [comment]
lgtm

**Comment by soc** [comment]
Good question. I think there is currently no real standard on that ... I think sbt-eclipse just uses `eclipse`, sbt-idea uses `gen-idea`, not really favoring anything here. Maybe we will see how many people will complain when they start using the new command (and reconsider)?

Thanks!

**Comment by fommil** [comment]
The old commands still work, but they are very noisy. Hopefully by starting with ensime in the name they are easier to find.

**Pull request merged**
