### PR TITLE
Increase heap size and add flags for Java 8

### LINKED ISSUE #319: add decent string/symbol table sizes
we should probably add this to the `ensimeJavaFlags` when java8+

```scala
    // print the table to optimise your own apps. VFS (and OrientDB)
    // are heavy on interning.
    javaOptions ++= Seq(
      //"-XX:+PrintStringTableStatistics",
      "-XX:StringTableSize=1000003",
      "-XX:+UnlockExperimentalVMOptions",
      "-XX:SymbolTableSize=1000003"
    ),
```

### PR DESCRIPTION
**Pull request by yyadavalli**
The tests are not updated yet. @fommil please confirm the changes are adequate.

Resolve #319, #324

### CODE REVIEW

**Comment by yyadavalli** [comment]
Also, the assertions need to be different based on JVM they are running on

**Comment by fommil** [comment]
I should already have a section for JavaFlags, it's best in there for the main project.

**Comment by yyadavalli** [comment]
Do you mean in sbt-sensible?

**Comment by fommil** [comment]
no, I think you found the right place. It might be cleaner to just shove the `Xmx` into the `ensimeJavaFlags` so that the user can override this. The JVM will always pick the most recent value.

**Comment by yyadavalli** [comment]
How about now, any idea on the tests I think only travis is running on Java 8

**Comment by fommil** [comment]
LGTM, but those damn test assertions need to be updated.

**Comment by fommil** [comment]
sorry, I merged another PR so this needs to be rebased

**Comment by yyadavalli** [comment]
No problem, did the rebase, if I add the java 8 flags the test assertions are going to fail in Appveyor and drone. That's the only thing stopping me.

**Comment by fommil** [comment]
oh I see. btw maybe we should do the test the other way around... check for not java 6 or 7. (are they valid for java 7? Not really relevant I guess)

**Comment by fommil** [comment]
I'm patching this up, I'll push here if I can

**Comment by fommil** [comment]
oh damn, of course OS X and Windows CI are using Java 8, aren't they.

**Comment by yyadavalli** [comment]
@fommil thanks for doing this. Sorry couldn't get to it earlier, was busy studying for an exam.

**Pull request merged**
