### PR TITLE
No deprecated

### LINKED ISSUE #263: remove deprecated APIs
since 1.11.3 we should now have an improved dev experience using macros, so we don't really have a strong excuse anymore for using the deprecated APIs.

### PR DESCRIPTION
**Pull request by fommil**
close #263

### CODE REVIEW

**Comment by fommil** [comment]
@dwijnand and you didn't even have to do it this time

**Comment by dwijnand** [comment]
Wohoo! Happy days. I'm happy ENSIME now doesn't force users to avoid macros.

**Comment by fommil** [comment]
Still no .sbt support, but i deal with that by using plugins

**Comment by dwijnand** [comment]
Happy to help where I can in sbt to help ENSIME handle sbt files.

**Pull request merged**
